version: '3.7'

services:
  database:
    image: postgres
    container_name: database_typescript
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=typescript
    volumes:
      - pgdata:/data/postgres
      
  app:
    build: .
    container_name: typescript
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app


volumes:
  pgdata:
    driver: local